service: trading_platform

provider:
  name: aws
  runtime: python3.6

package:
  exclude:
    - .*/**
  include:
    - trading_platform/**

plugins:
  - serverless-python-requirements

# The "functions" section shouldn't be needed because "package: individually" is not set to True,
# but if this section is taken out, serverless fails with an error:
# https://github.com/UnitedIncome/serverless-python-requirements/issues/161
functions:
  trading_platform:
    handler: trading_platform
    module: trading_platform
    package:
      include:
        - trading_platform

custom:
  pythonRequirements:
    dockerizePipe: true
    pipCmdExtraArgs:
      - --cache-dir
      - .requirements-cache